# fly.toml file generated for flash-dispatch
app = "flash-dispatch"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  DEBUG = "False"
  DJANGO_SETTINGS_MODULE = "flash_dispatch.settings"

[http_service]
  internal_port = 8060
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 8060
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"