# fly.toml app configuration file generated for flash-dispatch-transit on 2026-04-11T00:30:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flash-dispatch-transit'
primary_region = 'iad'

[build]
dockerfile = "Dockerfile"

[deploy]
release_command = "python manage.py migrate --noinput"

[env]
DEBUG = "False"
DJANGO_SETTINGS_MODULE = "flash_dispatch.settings"
PYTHONPATH = "/code"

[experimental]
auto_rollback = true

  [experimental.attached]
  secrets = { }

[[services]]
internal_port = 8_020
protocol = "tcp"

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "30s"
  interval = "15s"
  timeout = "5s"
    grace_period = "30s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"
