# Generated by Django 4.2 on 2026-03-25 01:38

import apps.tracking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        default=apps.tracking.models.generate_tracking_number,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                ("sender_address", models.TextField()),
                ("sender_phone", models.CharField(max_length=15)),
                ("sender_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_address", models.TextField()),
                ("recipient_phone", models.CharField(max_length=15)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dimensions",
                    models.CharField(help_text="LxWxH in cm", max_length=50),
                ),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Delivery"),
                            ("express", "Express Delivery"),
                            ("overnight", "Overnight"),
                            ("international", "International"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("estimated_delivery", models.DateField()),
                ("actual_delivery", models.DateField(blank=True, null=True)),
                ("current_location", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackingUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="tracking.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
