# Generated by Django 4.2 on 2026-03-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="document",
            field=models.ImageField(
                blank=True,
                help_text="Upload document or package image",
                null=True,
                upload_to="shipment_documents/",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="document_cloudinary_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="fragile_handling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="insurance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="signature_required",
            field=models.BooleanField(default=False),
        ),
    ]
